name: CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install and Build
      run: |
        git config user.email "martin.y.stoev@gmail.com"
        git config user.email "Martin Stoev"
        npm i
        npm run build
    - name: Deploy
      run: npm run deploy